//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerienMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieGenre
    {
        public int ID { get; set; }
        public Nullable<int> fk_Genre { get; set; }
        public Nullable<int> fk_Serie { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Serie Serie { get; set; }
    }
}
